{
 "title": "SCR Dashboard",
 "description": "SAS Container Runtime Monitoring Dashboard",
 "tags": [ "scr" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_app_kubernetes_io_component=\"scr\"},namespace)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_labels{label_workload_class=\"models\"},node)"
    }
   },
   {
    "name": "model",
    "label": "Model",
    "query": {
     "query": "label_values(scr_module_execution_count,model)"
    }
   },
   {
    "name": "application",
    "label": "Model Instance",
    "query": {
     "query": "label_values(scr_module_execution_count{model=\"$model\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# SAS Container Runtime Monitoring Dashboard"
   }
  },
  { "title": "Running SCR Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Running Models",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  count by (label_app_kubernetes_io_name) (\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_component=\"scr\"\r\n    }\r\n    * on (pod, namespace) group_left()\r\n    max by (pod, namespace) (\r\n      kube_pod_container_status_ready == 1\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Running Pods by Model/Decision",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 18, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_ready{pod=~\".*scr.*\"}) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Transactions per Minute",
   "type": "timeseries",
   "description": "The total number of execute calls that have been made since the container was started.\n\nMetrics:  scr_module_execution_count",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (model) (rate(scr_module_execution_count[$__rate_interval]) * 30)\r\n",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Detailed View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "The Detailed View is designed to report on a single model, or you can select multiple models for model comparison.",
     "type": "text",
     "gridPos": { "h": 1, "w": 22, "x": 0, "y": 212 }
    },
    {
     "title": "Pods by Model/Decision",
     "type": "table",
     "description": "Real-time view of the SCR deployments / pods.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count ((kube_pod_labels{label_app_kubernetes_io_name=~\"$model\"}) * on (pod) group_left(model)\r\n  (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_app_kubernetes_io_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pods by Model/Decision",
     "type": "barchart",
     "description": "Time series showing the SCR deployments / pods.",
     "gridPos": { "h": 7, "w": 14, "x": 8, "y": 260 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "count ((kube_pod_labels{label_app_kubernetes_io_name=~\"$model\"}) * on (pod) group_left(model)\r\n  (kube_pod_status_phase{phase=\"Running\"} == 1)) by (label_app_kubernetes_io_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Calls by Model / Decision",
     "type": "table",
     "description": "The total number of execute calls that have been made since the container was started.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 267 },
     "targets": [
      {
       "expr": "sum(scr_module_execution_count{model=~\"$model\"}) by (container)"
      }
     ]
    },
    {
     "title": "Total Calls by Model / Decision",
     "type": "timeseries",
     "description": "The total number of execute calls that have been made since the container was started.",
     "gridPos": { "h": 8, "w": 14, "x": 8, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(scr_module_execution_count{model=~\"$model\"}) by (container)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Calls by Pod",
     "type": "timeseries",
     "description": "The total number of execute calls that have been made since the container was started.",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 275 },
     "targets": [
      {
       "expr": "scr_module_execution_count{model=~\"$model\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Execution Time by Pod",
     "type": "timeseries",
     "description": "The total time spent executing user requests (in milliseconds).\n\nMetrics: scr_module_execution_sum",
     "gridPos": { "h": 11, "w": 14, "x": 8, "y": 275 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(scr_module_execution_sum{model=~\"$model\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "The Resource View is designed to report on a single model, or you can select multiple models for model comparison.",
     "type": "text",
     "gridPos": { "h": 1, "w": 21, "x": 0, "y": 18 }
    },
    {
     "title": "SCR Pod Quality of Service (QoS)",
     "type": "table",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "max by (namespace, pod, node, qos_class) (\r\n  (\r\n    (kube_pod_status_qos_class == 1)\r\n      * on (pod, namespace) group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"} == 1)\r\n      * on (pod, namespace) group_left()\r\n    (kube_pod_labels{label_app_kubernetes_io_name=~\"$model\"})\r\n  )\r\n  * on (namespace, pod) group_left(node)\r\n  kube_pod_info\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    { "title": "Resource Quotas", "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 27 } },
    {
     "title": "CPU Quota (Requests, Limits and Usage)",
     "type": "table",
     "description": "This table has filtered out non-model pods.",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(\r\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n * 1000) by (pod)"
      },
      {
       "expr": "sum(\r\n  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{\r\n    cluster=\"$cluster\",\r\n    namespace=\"$namespace\"\r\n  }\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n * 1000) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n * 1000) by (pod)"
      },
      {
       "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate5m{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod) / sum(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod)"
      }
     ]
    },
    {
     "title": "Memory Quotas (Requests, Limits and Usage)",
     "type": "table",
     "description": "This table has filtered out non-model pods.",
     "gridPos": { "h": 8, "w": 23, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\".*$model.*\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod)"
      },
      {
       "expr": "sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      },
      {
       "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\", image!=\"\", pod=~\".*$model.*\"}) by (pod) / sum(cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{cluster=\"$cluster\", namespace=\"$namespace\", pod=~\".*$model.*\"}) by (pod)"
      },
      {
       "expr": "sum(container_memory_rss{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      },
      {
       "expr": "sum(container_memory_cache{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      },
      {
       "expr": "sum(container_memory_swap{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}\r\n  * on (namespace, pod)\r\n    group_left\r\n    kube_pod_labels{\r\n      label_app_kubernetes_io_name=~\"$model\"\r\n    }\r\n) by (pod)"
      }
     ]
    },
    { "title": "Resource Usage", "type": "text", "gridPos": { "h": 1, "w": 23, "x": 0, "y": 44 } },
    {
     "title": "SCR Memory by Pod",
     "type": "table",
     "description": "Current memory that is used by the SCR components.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "scr_memory_used_bytes{model=~\"$model\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "User CPU Time (by SCR Pod)",
     "type": "timeseries",
     "description": "The user CPU time since the start-up of the container (in microseconds).\n\nThe gauge is showing the average user CPU time over the interval period. ",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "rate(scr_user_cpu_time{model=~\"$model\"}[$__rate_interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{\r\n  namespace=\"$namespace\", pod=~\".*$model.*\"}[$__rate_interval])\r\n  )\r\nby (pod)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{\r\n  namespace=\"$namespace\", pod=~\".*$model.*\"}[$__rate_interval])\r\n  )\r\nby (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 21, "x": 0, "y": 1497 },
     "options": {
      "content": "#### JVM details for a model instance (pod)\r\n\r\n*Note, only one model and model instance (pod) can be selected for the JVM reporting.*"
     }
    },
    {
     "title": "JVM Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 1526 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_current{model=\"$model\", pod=\"$application\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "jvm_threads_peak{model=\"$model\", pod=\"$application\"}",
       "legendFormat": "Peak"
      },
      {
       "expr": "jvm_threads_daemon{model=\"$model\", pod=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_deadlocked{model=\"$model\", pod=\"$application\"}",
       "legendFormat": "Deadlocked"
      }
     ]
    },
    {
     "title": "JVM Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 1526 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_state{model=\"$model\", pod=\"$application\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Resident Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1533 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod, container) (\r\n  container_memory_rss{pod=\"$application\", container!=\"POD\", container!=\"\"}\r\n)",
       "legendFormat": "Container Memory RSS"
      }
     ]
    },
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 1533 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_init_bytes{pod=\"$application\", area=\"heap\"})",
       "legendFormat": "init"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$application\", area=\"heap\"})",
       "legendFormat": "commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$application\", area=\"heap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Non-Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1533 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_init_bytes{pod=\"$application\", area=\"nonheap\"})",
       "legendFormat": "init"
      },
      {
       "expr": "sum(jvm_memory_committed_bytes{pod=\"$application\", area=\"nonheap\"})",
       "legendFormat": "commited"
      },
      {
       "expr": "sum(jvm_memory_max_bytes{pod=\"$application\", area=\"nonheap\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Allocated: CodeHeap)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_allocated_bytes_total",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1541 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"CodeHeap 'non-nmethods'\"})",
       "legendFormat": "non-nmethods"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"CodeHeap 'non-profiled nmethods'\"})",
       "legendFormat": "non-profiled nmethods"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"CodeHeap 'profiled nmethods'\"})",
       "legendFormat": "profiled nmethods"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Allocated)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_allocated_bytes_total",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1541 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"Compressed Class Space\"})",
       "legendFormat": "Compressed Class Space"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"G1 Eden Space\"})",
       "legendFormat": "G1 Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"G1 Old Gen\"})",
       "legendFormat": "G1 Old Gen"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"G1 Survivor Space\"})",
       "legendFormat": "G1 Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_allocated_bytes_total{pod=\"$application\", pool=\"Metaspace\"})",
       "legendFormat": "Metaspace"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Used)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_used_bytes",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1541 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"CodeHeap 'non-nmethods'\"})",
       "legendFormat": "CodeHeap: 'non-nmethods'"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"CodeHeap 'non-profiled nmethods'\"})",
       "legendFormat": "CodeHeap: 'non-profiled nmethods'"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"CodeHeap 'profiled nmethods'\"})",
       "legendFormat": "CodeHeap: 'profiled nmethods'"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"Compressed Class Space\"})",
       "legendFormat": "Compressed Class Space"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"Eden Space\"})",
       "legendFormat": "Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"Metaspace\"})",
       "legendFormat": "Metaspace"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"Survivor Space\"})",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_used_bytes{pod=\"$application\", pool=\"Tenured Gen\"})",
       "legendFormat": "Tenured Gen"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Collection Max)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_collection_max_bytes",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1550 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"G1 Eden Space\"})",
       "legendFormat": "G1 Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"G1 Old Gen\"})",
       "legendFormat": "G1 Old Gen"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"G1 Survivor Space\"})",
       "legendFormat": "G1 Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"Eden Space\"})",
       "legendFormat": "Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"Survivor Space\"})",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_max_bytes{pod=\"$application\", pool=\"Tenured Gen\"})",
       "legendFormat": "Tenured Gen"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Collection Init)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_collection_init_bytes",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1550 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"G1 Eden Space\"})",
       "legendFormat": "G1 Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"G1 Old Gen\"})",
       "legendFormat": "G1 Old Gen"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"G1 Survivor Space\"})",
       "legendFormat": "G1 Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"Eden Space\"})",
       "legendFormat": "Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"Survivor Space\"})",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_init_bytes{pod=\"$application\", pool=\"Tenured Gen\"})",
       "legendFormat": "Tenured Gen"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Collection Committed)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_collection_committed_bytes",
     "gridPos": { "h": 9, "w": 7, "x": 14, "y": 1550 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"G1 Eden Space\"})",
       "legendFormat": "G1 Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"G1 Old Gen\"})",
       "legendFormat": "G1 Old Gen"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"G1 Survivor Space\"})",
       "legendFormat": "G1 Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"Eden Space\"})",
       "legendFormat": "Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"Survivor Space\"})",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_committed_bytes{pod=\"$application\", pool=\"Tenured Gen\"})",
       "legendFormat": "Tenured Gen"
      }
     ]
    },
    {
     "title": "JVM Memory Pool (Collection Used)",
     "type": "timeseries",
     "description": "Metrics: jvm_memory_pool_collection_used_bytes",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1559 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"G1 Eden Space\"})",
       "legendFormat": "G1 Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"G1 Old Gen\"})",
       "legendFormat": "G1 Old Gen"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"G1 Survivor Space\"})",
       "legendFormat": "G1 Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"Eden Space\"})",
       "legendFormat": "Eden Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"Survivor Space\"})",
       "legendFormat": "Survivor Space"
      },
      {
       "expr": "sum(jvm_memory_pool_collection_used_bytes{pod=\"$application\", pool=\"Tenured Gen\"})",
       "legendFormat": "Tenured Gen"
      }
     ]
    },
    {
     "title": "JVM Classes",
     "type": "timeseries",
     "description": "Metrics: jvm_classes_currently_loaded and jvm_classes_loaded_total",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1559 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(jvm_classes_currently_loaded)",
       "legendFormat": "Currently loaded"
      },
      { "expr": "sum(jvm_classes_loaded_total)", "legendFormat": "Total loaded" }
     ]
    },
    {
     "title": "Garbage Collection Notes",
     "type": "text",
     "gridPos": { "h": 13, "w": 7, "x": 14, "y": 1559 },
     "options": {
      "content": "<details>\n<summary>Expand to see details.</summary>\n\n* `jvm_gc_collection_seconds_count`: measures how many GC events occurred.\n* `jvm_gc_collection_seconds_sum`: the total time (in seconds) spent doing GC across those events.\n\nThe G1 Concurrent GC metric measures the time spent in Garbage-First (G1) collector's concurrent marking and cleanup phases, specifically tracking JVM garbage collection CPU time.\n\nG1 Young Generation metrics measure the frequency and duration of Garbage First (G1) Garbage Collector \"stop-the-world\" pauses specifically targeting Eden and Survivor regions.\n\nThe \"G1 Old Generation\" metric monitors memory usage and garbage collection activity within the old generation heap region of the Garbage-First (G1) collector.\n\nThe \"Copy\" metrics refers to the Copying Garbage Collector used in the Young Generation (Eden and Survivor spaces), which moves live objects from one memory space to another. \n\n\n\n</details>"
     }
    },
    {
     "title": "Garbage Collection (Events per minute)",
     "type": "timeseries",
     "description": "Metrics: jvm_gc_collection_seconds_count\n\nThe G1 Concurrent GC metric measures the time spent in Garbage-First (G1) collector's concurrent marking and cleanup phases, specifically tracking JVM garbage collection CPU time.\n\nG1 Young Generation metrics measure the frequency and duration of Garbage First (G1) Garbage Collector \"stop-the-world\" pauses specifically targeting Eden and Survivor regions.\n\n",
     "gridPos": { "h": 9, "w": 7, "x": 0, "y": 1568 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{gc=\"G1 Concurrent GC\", pod=\"$application\"}[1m])) * 60",
       "legendFormat": "G1 Concurrent GC"
      },
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{gc=\"G1 Old Generation\", pod=\"$application\"}[1m])) * 60",
       "legendFormat": "G1 Old Generation"
      },
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\", pod=\"$application\"}[1m])) * 60",
       "legendFormat": "G1 Young Generation"
      },
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{gc=\"Copy\", pod=\"$application\"}[1m])) * 60",
       "legendFormat": "Copy"
      },
      {
       "expr": "sum(rate(jvm_gc_collection_seconds_count{gc=\"MarkSweepCompact\", pod=\"$application\"}[1m])) * 60",
       "legendFormat": "MarkSweepCompact"
      }
     ]
    },
    {
     "title": "Garbage Collection (Sum)",
     "type": "timeseries",
     "description": "Metrics: jvm_gc_collection_seconds_count and jvm_gc_collection_seconds_sum",
     "gridPos": { "h": 9, "w": 7, "x": 7, "y": 1568 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Concurrent GC\", pod=\"$application\"}[5m])",
       "legendFormat": "G1 Concurrent GC"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Old Generation\", pod=\"$application\"}[5m])",
       "legendFormat": "G1 Old Generation"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\", pod=\"$application\"}[5m])",
       "legendFormat": "G1 Young Generation"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"Copy\", pod=\"$application\"}[5m])",
       "legendFormat": "Copy"
      },
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{gc=\"MarkSweepCompact\", pod=\"$application\"}[5m])",
       "legendFormat": "MarkSweepCompact"
      }
     ]
    }
   ]
  },
  {
   "title": "Node View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    { "title": "Reporting on node: $node", "type": "text", "gridPos": { "h": 1, "w": 18, "x": 0, "y": 423 } },
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(machine_cpu_cores{node=\"$node\", cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 3, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{job=\"node-exporter\", nodename=~\"$node\"}\r\n\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 6, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\r\n  node_memory_MemTotal_bytes{job=\"node-exporter\", nodename=~\"$node\"}\r\n  -\r\n  node_memory_MemAvailable_bytes{job=\"node-exporter\", nodename=~\"$node\"}\r\n)\r\n/\r\nnode_memory_MemTotal_bytes{job=\"node-exporter\", nodename=~\"$node\"}\r\n* 100\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "description": "Sum all the CPU modes except for idle, iowait, guest, and guest_nice.",
     "gridPos": { "h": 7, "w": 9, "x": 9, "y": 424 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (node) (\r\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", nodename=~\"$node\"}[$__rate_interval]))\r\n/ ignoring(cpu) group_left\r\n  count without (cpu)(node_cpu_seconds_total{job=\"node-exporter\", mode=~\"idle|iowait|guest|guest_nice\", nodename=~\"$node\"})\r\n)",
       "legendFormat": "Utilisation"
      }
     ]
    },
    { "title": "Pod details for node: $node", "type": "text", "gridPos": { "h": 1, "w": 18, "x": 0, "y": 431 } },
    {
     "title": "Pods on node",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 432 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_pod_info{node=\"$node\", cluster=\"$cluster\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "List of pods on node",
     "type": "table",
     "gridPos": { "h": 10, "w": 14, "x": 4, "y": 432 },
     "targets": [
      {
       "expr": "kube_pod_info{node=\"$node\", cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "SCR Pod Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 437 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(\r\n  kube_pod_labels{label_app_kubernetes_io_component=\"scr\"} \r\n  * on(pod, namespace) group_left(node) \r\n  kube_pod_info{node=\"$node\"}\r\n)\r\n",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Dashboard Usage Notes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 11, "w": 22, "x": 0, "y": 909 },
     "options": {
      "content": "<p>\n  This dashboard is provided as an example of what is possible for monitoring the\n  SAS Container Runtime deployments.\n</p>\n\n<p>\n  For the dashboard to function it is expecting the SAS Container Runtime pods to have\n  the following labels:\n</p>\n\n<ul>\n  <li><strong>app.kubernetes.io/name</strong></li>\n  <li><strong>app.kubernetes.io/component</strong></li>\n</ul>\n\n<p>\n  The above labels are not only used in the PromQL queries; the\n  <code>app.kubernetes.io/component</code> label is also used to create a filtered list\n  of namespaces.\n</p>\n\n<p>\n  While the dashboard endeavours to make the reporting independent of the pod names,\n  there are queries that rely on regular expression matching using: <code>pod=~\".*&#36;model.*\"</code>\n</p>\n<p>\n  This was necessary as not all metrics data includes the Kubernetes labels. However,\n  it does require that the model name is part of the pod name. For example,\n  <em>qsreg1-scr-model</em> or <em>riskscore-model</em>.\n</p>\n\n<p>\n  The <strong>Node View</strong> reporting assumes any nodes dedicated to running the SAS Container Runtime\n  pods have the following label:\n</p>\n\n<ul>\n  <li><strong>workload/class=models</strong></li>\n</ul>\n\n<p>\n  <em>\n    Please note, the dashboard is provided as a sample and has not been put through\n    comprehensive validation testing. It is maintained on an ad-hoc basis.\n  </em>\n</p>"
     }
    }
   ]
  }
 ]
}