{
 "title": "SAS Viya Summary",
 "tags": [ "sas-viya" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{label_sas_com_deployment=~\"sas-viya\"},namespace)"
    }
   },
   {
    "name": "depop",
    "label": "depop",
    "query": "label_values(kube_pod_labels{label_app_kubernetes_io_name=~\"sas-deployment-operator\"},label_app_kubernetes_io_name)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "casServer",
    "label": "CAS Server",
    "query": {
     "query": "label_values(cas_build_info{namespace=~\"$namespace\"},cas_server)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 14, "x": 0, "y": 0 }, "options": { "content": "# SAS Viya Overview" } },
  { "title": "Status Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Deployment Operator Status",
   "type": "stat",
   "description": "Displays the current status for the SAS Deployment Operator if found (Detected) in the namespace.\n\nWhen the operator is deploying SAS Viya it has the following states: PENDING --> RECONCILING --> SUCCEEDED\n\nFor this gauge the RECONCILING state is displayed as RUNNING.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    kube_pod_status_phase{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\",phase=\"Unknown\"} * 1\r\n  or\r\n    kube_pod_status_phase{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\",phase=\"Failed\"} * 2\r\n  or\r\n    kube_pod_status_phase{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\",phase=\"Pending\"} * 3\r\n  or\r\n    kube_pod_status_phase{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\",phase=\"Running\"} * 4\r\n  or\r\n    kube_pod_status_phase{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\",phase=\"Succeeded\"} * 5\r\n  )\r\n)\r\nOR on() vector(0)",
     "legendFormat": "Phase"
    },
    {
     "expr": "max(kube_pod_start_time{namespace=\"$namespace\",pod=~\"sas-deployment-operator-.*\"}) * 1000",
     "legendFormat": "Runtime"
    }
   ]
  },
  {
   "title": "Platform Readiness",
   "type": "status-history",
   "description": "Displays the readiness condition for the sas-readiness pod.",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{\r\n  namespace=\"$namespace\",\r\n  pod=~\"sas-readiness.*\",\r\n  condition=\"true\"\r\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SAS Viya Cadence Information",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_namespace_labels{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Health Overview", "type": "text", "gridPos": { "h": 1, "w": 18, "x": 0, "y": 7 } },
  {
   "title": "StatefulSets",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kube_statefulset_status_replicas_ready{namespace=\"$namespace\"} / kube_statefulset_replicas{namespace=\"$namespace\"}) * 100",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_deployment_status_replicas{namespace=\"$namespace\", deployment=~\".*sas.*\"}\r\n) \r\n",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(\r\n  kube_deployment_status_replicas_available{namespace=\"$namespace\", deployment=~\".*sas.*\"}\r\n) \r\n/ \r\nsum(\r\n  kube_deployment_spec_replicas{namespace=\"$namespace\", deployment=~\".*sas.*\"}\r\n) * 100",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Daemonset",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_daemonset_status_number_ready{namespace=\"$namespace\"}) \r\n/ \r\nsum(kube_daemonset_status_number_available{namespace=\"$namespace\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy / Ingress",
   "type": "gauge",
   "description": "Displays the percentage health for the HTTPproxy and an estimated value for the ingress definitions.",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_max(\r\nsum(kube_service_created{namespace=\"$namespace\", service=~\"sas.*\"}) /\r\nsum(kube_ingress_created{namespace=\"$namespace\"}) * 100, 100\r\n)",
     "legendFormat": "Ingress"
    },
    {
     "expr": "sum(contour_httpproxy_valid{exported_namespace=\"$namespace\"}) \r\n/ \r\nsum(contour_httpproxy{exported_namespace=\"$namespace\"}) * 100",
     "legendFormat": "Proxy"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 9, "x": 9, "y": 15 } },
  {
   "title": "PVC Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\", phase=\"Bound\"})/\r\nsum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\"}) * 100",
     "legendFormat": "Bound"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\", phase=\"Pending\"})/\r\nsum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\"}) * 100",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_status_phase{\r\n    namespace=~\"$namespace\",\r\n    pod=~\".*sas.*\",\r\n    phase=~\"Running|Pending|Failed|Unknown|Succeeded\"\r\n  }\r\n) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Status History",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_status_phase{\r\n    namespace=~\"$namespace\",\r\n    pod=~\"sas.*\",\r\n    phase=~\"Running|Pending|Failed|Unknown|Succeeded\"\r\n  }\r\n) by (phase)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReplicaSets, PVC details...",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReplicaSet Summary",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (phase) (\r\n  label_replace(\r\n    kube_pod_status_phase{\r\n      namespace=\"$namespace\",\r\n      phase=~\"Running|Pending|Failed|Succeeded|Unknown\"\r\n    }\r\n    * on (namespace, pod)\r\n      group_left(owner_name)\r\n      kube_pod_owner{\r\n        namespace=\"$namespace\",\r\n        owner_kind=\"ReplicaSet\",\r\n        owner_name=~\".*sas.*\"\r\n      },\r\n    \"deployment\", \"$1\", \"owner_name\", \"(.+)-[a-f0-9]{9,10}$\"\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Daemonset Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 6, "y": 26 },
     "targets": [
      {
       "expr": "kube_daemonset_status_number_ready{namespace=\"$namespace\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    { "title": "PVC Information", "type": "text", "gridPos": { "h": 1, "w": 20, "x": 0, "y": 33 } },
    {
     "title": "Total PVC",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Persistent Volume Information",
     "type": "table",
     "gridPos": { "h": 8, "w": 13, "x": 3, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{\r\n  namespace=\"$namespace\"\r\n}\r\n* on (namespace, persistentvolumeclaim)\r\n  group_left(storageclass, volume, volumemode)\r\n  kube_persistentvolumeclaim_info{\r\n    namespace=\"$namespace\"\r\n  }",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions and Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compute Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\",pod=~\"sas-compute-server-.*\"})",
       "legendFormat": "Compute"
      },
      {
       "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\", phase=\"Running\",pod=~\"sas-batch-server-.*\"})",
       "legendFormat": "Batch"
      }
     ]
    },
    {
     "title": "CAS Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 10, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cas_grid_sessions_current{namespace=\"$namespace\", cas_server=\"$casServer\", service=~\".+-client\"})",
       "legendFormat": "CAS sessions"
      }
     ]
    },
    {
     "title": "Completed CronJobs",
     "type": "table",
     "description": "The table shows the successfully completed conjob counts. One off jobs, such as the \"sas-pyconfig-cjinitial\" have been filtered out.",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "count by (job_group) (\r\n  label_replace(\r\n    kube_job_status_succeeded{\r\n      namespace=\"$namespace\",\r\n      job_name=~\".*-[0-9]+\"\r\n    } > 0,\r\n    \"job_group\",\r\n    \"$1\",\r\n    \"job_name\",\r\n    \"(.*)-[0-9]+\"\r\n  )\r\n)\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}